### ISSUE TITLE
STA/OPR 9750 SethKauf MiniProject #02

### ISSUE THREAD

**Issue by SethKauf** [SethKauf/STA9750-2024-FALL#4]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #02 - check it out!

https://SethKauf.github.io/STA9750-2024-FALL/mp02.html

**Comment by michaelweylandt** [comment]
Hi @SethKauf 

Do you want to take a look at this again? It looks like most of your text got swallowed up.

**Comment by SethKauf** [comment]
Hi @michaelweylandt 

The webpage change took a lot longer to upload than I thought, but it seems it finally went through. Please look at it again at your convenience.

**Comment by michaelweylandt** [comment]
Thanks @SethKauf !

Peer Feedback:

- @katariasiddhi
- @lavs10
- @Cdiallo77
- @YantingZhao11

It is now time for the peer feedback round for Mini-Project 02. Please
review @SethKauf's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini02.html#rubric,
please grade their submission out of a total of 50 points. Note that this
rubric is slightly different than that used for Mini-Project 01.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @SethKauf, but you are of course
welcome to initiate a discussion.

@SethKauf: please engage fully with your peers. They are here to help you!

Submission URL should be: https://SethKauf.github.io/STA9750-2024-FALL/mp02.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by katariasiddhi** [comment]
Hello @SethKauf,

Written Communication: Excellent (10/10) - The report is well-organized and flows smoothly from one idea to the next. Every step is described in detail, making it simple to understand the reasoning behind important actions. Your emphasis on key results and straightforward, captivating writing style successfully lead the reader.

Project Skeleton: Excellent (10/10) - The project fully addresses every task, demonstrating thoroughness and attention to detail. The answers are perceptive, demonstrate a thorough comprehension of the goals, and are executed with care.

Formatting & Display: Excellent (10/10) - The graphs and pictures greatly enhance the reading and understanding of the material, and the website style is well-designed. These images have been formatted and presented well. 

Code Quality: Excellent (10/10) - The code is concise, efficient, and logically organized. Each segment is thoughtfully commented on, explaining the purpose of specific functions rather than just restating them. This allows readers to understand not only what the code does but why each step is necessary.

Data Preparation (10/10) - Incorporating more images to improve data understanding was a good idea. Your use of pictures and graphs adds a lot of value and simplifies the interpretation of the codes.

Overall Suggestions: 50/50 -  covered all elements with care and precision, making this an outstanding submission.

**Comment by YantingZhao11** [comment]
Hi @SethKauf,

Please see the below.

Written Communication: 9/10
The writing is engaging and effectively explains each task. Adding smoother transitions between tasks could enhance the flow.

Project Structure: 10/10
Every task is fully addressed with detail and insight, showing a strong understanding of project goals and objectives.

Formatting & Display: 8/10
Graphs and visuals are well-chosen and enhance comprehension, but formalizing tables in tasks 2 and 5 could improve readability.

Code Quality: 10/10
The code is efficient, well-organized, and clearly commented, explaining each function’s purpose to aid understanding.

Data Preparation: 10/10

Overall:47/50

Thanks,
Yanting

**Comment by Cdiallo77** [comment]
Hello Hello @SethKauf 

Written Communication: 10/10
Your communication style is very captivating, you had an interesting line at every steps to engage with your reader. Not only that, but you also provided ample explanation for each question - zero ambiguity.  

Project Structure: 10/10
The objective is to answer all the question and you did deliver. Starting with the last task shows that you put extra effort to rearrange and make this assignment enjoyable. 

Formatting & Display: 8/10
Graphs and visuals were good except for #task 4. I find the plt a bit messy and noisy. Also, I suggest you on the next project to find a way to dropdown for all your lines of code.  

Code Quality: 10/10
The code line are well-organized and you commented each step, especially on your criteria for Flop and Top movies; which is good.

Data Preparation: 10/10

Overall:48/50

Great job!
